#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.)

set -e

cd ../../..

files="boost/lmp.hpp
$(find -type f -path '*/lmp/*' -a -not -path '*/.svn*' -a -not -name '.*' -a -not -name '*~' -a -not -name '*.o' | sed 's#^\./##g' | sort)"
tag="snapshot_$(date '+%Y%m%d')"

cd libs/lmp/

cd script
./Make-lmp-hpp
cd ..

cd example
./Test-all
cd ..

cd test
./Test-all
cd ..

cd ../..

tar -cjf  ../lmp_$tag.tar.bz2 $files
tar -czf  ../lmp_$tag.tar.gz  $files
zip -9 -q ../lmp_$tag.zip     $files
