#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.)

set -e

TIMEFORMAT='%R seconds'

rootDir="../../.."

if test -d "$rootDir/../boost" ; then
    boostInc="-I $rootDir/../boost"
    echo "Including Boost through '$boostInc'."
else
    boostInc=''
    echo "Using system version of Boost."
fi

function compile {
    g++ -c -std=c++98 -Wall -pedantic -I "$rootDir" $boostInc -o Test.o "$@"
    rm Test.o
}

time for f in bench_*.cpp ; do
    echo -n "$f: "
    time compile "$f"
done
